# hugo.toml
baseURL = "https://structureandsense.org/"
languageCode = "en"
title = "Structure & Sense"
enableRobotsTXT = true

# Disqus shortname
#disqusShortname = ""
# google analytics tracking id
#googleAnalytics = ""
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2025 Structure and Sense"

[params]
  # useCDN = false
  # showShareIcons = true
  # Date format
  #dateFormat = "January 2, 2006"
  # Put images/favicon.ico file
  favicon = "img/favicon.ico"

# This is displayer in About page.
[params.author]
  name = "Foo Bar"

  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  #x = "X username"
  #twitter = "Twitter username"
  #facebook = "Facebook username"
  #googleplus = "Googleplus username"
  #instagram = "Instagram username"
  #threads = "Threads username"
  #tumblr = "Tumblr username"
  #flickr = "Flickr username"
  #reddit = "Reddit username"
  #linkedin = "Linkedin username"
  #slideshare = "Slideshare username"
  #github = "Github username"
  #gitlab = "Gitlab username"
  #bitbucket = "Bitbucket username"
  #stackoverflow = "Stackoverflow username"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"
  #deviantart = "Deviantart username"
  #behance = "Behance username"
  #dribbble = "Dribbble username"
  #wordpress = "Wordpress username"
  #medium = "Medium username"
  #foursquare = "Foursquare username"
  #xing = "Xing username"
  #quora = "Quora username"
  #youtube = "YouTube username"
  #tiktok = "TikTok username"
  #vimeo = "Vimeo username"
  #whatsapp = "Whatsapp username"
  #skype = "Skype username"
  #snapchat = "Snapchat username"
  #pinterest = "Pinterest username"
  #telegram = "Telegram username"
  #vine = "Vine username"
  #email = "Your email"

[[params.author.social]]
  name = "Custom social link1"
  iclass = "fa-brands fa-github"
  url = "https://github.com/TimothyElder/hugo.structure-sense"

[[params.author.social]]
  name = "Custom social link2"
  iclass = "fa-brands fa-google"
  url = "https://example.com/whiteplain"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
pages = "/:slug/"

[[menu.main]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Aims"
  weight = 2
  identifier = "aims"
  url = "/aims/"
[[menu.main]]
  name = "Submit"
  weight = 3
  identifier = "submit"
  url = "/submit/"
[[menu.main]]
  name = "Contact"
  weight = 4
  identifier = "contact"
  url = "/contact/"
#[[menu.main]]
#  name = "Categories"
#  weight = 4
#  identifier = "categories"
#  url = "/categories/"
#[[menu.main]]
#  name = "Tags"
#  weight = 5
#  identifier = "tags"
#  url = "/tags/"
#[[menu.main]]
#  name = "Archives"
#  weight = 6
#  identifier = "archives"
#  url = "/archives/"

[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
[[menu.footer]]
  name = "Contact"
  weight = 2
  identifier = "contact"
  url = "/contact/"
[[menu.footer]]
  name = "Policies"
  weight = 3
  identifier = "policies"
  url = "/pages/policies/"