# hugo.toml
baseURL = "https://structureandsense.org/"
languageCode = "en"
title = "Structure & Sense"
enableRobotsTXT = true
theme = "whiteplain"
# Disqus shortname
#disqusShortname = ""
# google analytics tracking id
#googleAnalytics = ""
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2025 Sense & Structure"

[params]
  # useCDN = false
  # showShareIcons = true
  # Date format
  #dateFormat = "January 2, 2006"
  # Put images/favicon.ico file
  #favicon = "images/favicon.ico"

# This is displayer in About page.
[params.author]
  name = "Foo Bar"

  # Gravatar or Abatar image
  #gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  #x = "X username"
  #twitter = "Twitter username"
  #facebook = "Facebook username"
  #googleplus = "Googleplus username"
  #instagram = "Instagram username"
  #threads = "Threads username"
  #tumblr = "Tumblr username"
  #flickr = "Flickr username"
  #reddit = "Reddit username"
  #linkedin = "Linkedin username"
  #slideshare = "Slideshare username"
  #github = "Github username"
  #gitlab = "Gitlab username"
  #bitbucket = "Bitbucket username"
  #stackoverflow = "Stackoverflow username"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"
  #deviantart = "Deviantart username"
  #behance = "Behance username"
  #dribbble = "Dribbble username"
  #wordpress = "Wordpress username"
  #medium = "Medium username"
  #foursquare = "Foursquare username"
  #xing = "Xing username"
  #quora = "Quora username"
  #youtube = "YouTube username"
  #tiktok = "TikTok username"
  #vimeo = "Vimeo username"
  #whatsapp = "Whatsapp username"
  #skype = "Skype username"
  #snapchat = "Snapchat username"
  #pinterest = "Pinterest username"
  #telegram = "Telegram username"
  #vine = "Vine username"
  #email = "Your email"

[[params.author.social]]
  name = "Custom social link1"
  iclass = "fa-brands fa-github"
  url = "https://example.com/whiteplain"

[[params.author.social]]
  name = "Custom social link2"
  iclass = "fa-brands fa-google"
  url = "https://example.com/whiteplain"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
